package model.utility;

public enum BoatType {
	BASS_BOAT,
	BAY_BOAT,
	BOWRIDER,
	CENTER_CONSOLE,
	CONVERTABLE_FISHING_BOAT,
	CRUISER,
	CUDDY_CABIN,
	DECK_BOAT,
	DINGHY,
	DOWNEAST_CRUISER,
	DUAL_CONSOLE,
	EXPRESS_FISHERMAN
	/**
	 * Can also be extended to hold these types:
	FISHING_SKI_BOAT,
	FLATS_BOAT,
	HIGH_PERFORMANCE_BOAT,
	HOUSE_BOAT,
	JON_BOAT,
	JET_BOAT,
	MULTI_SPECIES_BOAT,
	PILOT_HOUSE_BOAT,
	PONTOON_BOAT,
	POWER_CATAMARAN,
	PERSONAL_WATERCRAFT,
	RUNABOUT,
	SKIFF
	*/
}
