package model.utility;

/*

INLINE_SINGLE,
INLINE_TWO_CYLINDER,
INLINE_THREE_CYLINDER,
INLINE_FOUR_CYLINDER,

*/
public enum EngineType {
	VEE,INLINE,STRAIGHT,BOXER,VR_AND_W,SINGLE,V_TWIN,TWO_CYLINDER, 	
	THREE_CYLINDER, FOUR_CYLINDER, SIX_CYLINDER, EIGHT_CYLINDER
}

